### ISSUE TITLE
Bot Stays offline in Discord after it Reconnects due to Discord Cloudfare reboot

### ISSUE THREAD

**Issue by xWolfx93** [DSharpPlus/DSharpPlus#425] opened 2019-05-02 08:19 UTC
Using D# 4 Nightly 000597.
As the title states after Discords Cloudfare reboot the Bot says in Console that it reconnects, but in Discord it stays offline.
DiscordClient Ready/Resume events do not fire in this case.

Will update with more infos as i gather them.

**Comment by uwx** [comment] 2019-06-17 06:16
To anyone who's been having this issue, please reply here with a few details about your setup:

* OS and version (e.g Windows 7)
* Platform and version (e.g .NET Core 2.2)
* WebSocket client (e.g 'none' or 'WebSocket4NetCore')
* Client sharding setup (either 'not sharded', 'DiscordShardedClient', or 'manually sharded')
* Amount of guilds you serve, if it's under 2500, otherwise just say it's over 2500

In addition, if possible, please include some details about the issue itself:

* What is logged to the console right before and during attempted reconnect
* When the issue occurs relative to bot startup time
* Does it affect all of your shards at once? It would be rather tricky to test this, but if by coincidence you share servers with your bot on multiple shards, and only some of them go offline, let me know

This issue is really fiddly and difficult to diagnose (I haven't even been able to reproduce it yet) so any details would be quite helpful.

**Comment by Kriste00** [comment] 2019-06-17 14:27
OS: Windows 10
Platform: .NET Core 2.1
WebSocket client : none
Sharding: manually sharded
Guilds: 2500

This can occur on any shard independent of eachoder and at random intervals.

Here is a screenshot of what is logged in the console when the bot is offline:
![bilde](https://user-images.githubusercontent.com/32580874/59611651-f742b780-911b-11e9-9400-ad752c440fa0.png)

Not a token issue since it works again after a simple restart

**Comment by WamWooWam** [comment] 2019-06-17 16:09
OS: Windows 10
Platform: .NET Core 2.0 via. UWP
WS Client: Default
Guilds: ~80

It's important to note this isn't just caused by the Cloudflare reboots, it can happen any time the WebSocket connection isn't cleanly closed, in my case it's generally caused by UWP suspending my app while in the background, or the system going to sleep.

**Comment by F1restar4** [comment] 2019-06-17 16:26
OS: Ubuntu 18.04 LTS
Platform: .NET Core 2.2
WS Client: default
Guilds: 4

Sometimes I'll have to restart the next day, sometimes it's a week later.
I can't wait for this to be fixed in twenty years

**Comment by jeffreyladd** [comment] 2019-06-17 22:16
OS: win 10
Platform:.net core 2.2
Websocket: none
Guilds: 2 Not Sharded

For me its kinda consistent on weekdays at 1am and 5 am.

**Closed** 2019-06-23 12:40 UTC
Labels: bug, core
