### ISSUE TITLE
Sending a file with an invalid name blocks sending other files/responses forever

### ISSUE THREAD

**Issue by Damitrix** [DSharpPlus/DSharpPlus#409] opened 2019-03-24 19:33 UTC
# Summary
When supplying DiscordChannel.SendFileAsync() with an invalid fileName 
`"This \"contains\" special letters.jpeg"`
the function will just await forever.

# Details
.Net Core 2.2
Win10 + Ubuntu 18.04 and 16.04
But i guess this will happen everywhere.

# Steps to reproduce
1. Await DiscordChannel.SendFileAsync(), with any filestream and supply a path with quotation marks
2. Wait for it to finish (output to console or wait for debug step)
3. It won't finish

# Notes
I haven't tested any other special characters.

**Comment by Emzi0767** [comment] 2019-03-28 06:30
Which D#+ version?

**Comment by uwx** [comment] 2019-03-28 07:18
Haven't tried to repro this yet, but it looks like it's an exception being swallowed by the REST client. The exception is thrown here:
https://github.com/dotnet/corefx/blob/a6f76f4f620cbe74821c6445af3f13e048361658/src/System.Net.Http/src/System/Net/Http/Headers/ContentDispositionHeaderValue.cs#L439-L443

**Comment by uwx** [comment] 2019-03-29 08:01
I think this is user error. After trying it myself, uploading a file with the exact name you provided throws up an exception (as it should upon encountering double quotes) and the bot continues to work normally (as it should upon encountering an exception). This is the exception that gets thrown:

```
System.ArgumentException: The format of value 'This "contains" special letters.jpeg' is invalid.
   at System.Net.Http.Headers.ContentDispositionHeaderValue.EncodeAndQuoteMime(String input)
   at System.Net.Http.Headers.ContentDispositionHeaderValue.SetName(String parameter, String value)
   at System.Net.Http.MultipartFormDataContent.AddInternal(HttpContent content, String name, String fileName)
   at System.Net.Http.MultipartFormDataContent.Add(HttpContent content, String name, String fileName)
   at DSharpPlus.Net.RestClient.BuildRequest(BaseRestRequest request) in F:\Stuff1tb\GitHub\Dsharp\RayBot2\DSharpPlus\DSharpPlus\Net\RestClient.cs:line 310
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync(BaseRestRequest request, RateLimitBucket bucket, TaskCompletionSource`1 ratelimitTcs) in F:\Stuff1tb\GitHub\Dsharp\RayBot2\DSharpPlus\DSharpPlus\Net\RestClient.cs:line 144
   at DSharpPlus.Net.DiscordApiClient.UploadFileAsync(UInt64 channel_id, Stream file_data, String file_name, String content, Nullable`1 tts, DiscordEmbed embed) in F:\Stuff1tb\GitHub\Dsharp\RayBot2\DSharpPlus\DSharpPlus\Net\DiscordApiClient.cs:line 579
   at RayBotSharp.Commands.Testing.TestDmsError3(Context ctx) in F:\Stuff1tb\GitHub\Dsharp\RayBot2\RayBotSharp\Commands\Testing.cs:line 144
   at RayBotSharp.CommandSystem.MessageCreated.TryExecuteCommand(InternalContext internalContext) in F:\Stuff1tb\GitHub\Dsharp\RayBot2\RayBotSharp\CommandSystem\MessageCreated.cs:line 243
```

As you can see, normal stuff, nothing weird. The only way I could see this deadlocking the bot would be some bug in 3.2 that was fixed in the nightlies after the REST client update.

More information needs to be provided for this to be an actual bug report, especially the code causing it to happen. What is your D#+ version? What command framework are you using? Are you using asynchronous events correctly? Are you hooking the relevant error events? Do other exceptions, like ones you throw yourself, also cause this behavior to occur?

**Comment by NaamloosDT** [comment] 2019-05-28 18:39
![](https://i.imgur.com/9wWsiEL.png)

to be fair, your filenames shouldn't contain those characters anyway

**Comment by uwx** [comment] 2019-05-28 18:40
> to be fair, your filenames shouldn't contain those characters anyway

I think some of those are allowed on Linux.

**Comment by NaamloosDT** [comment] 2019-05-28 18:40
they are? lemme check that

**Comment by uwx** [comment] 2019-05-28 18:41
"Any byte except NUL or /"

**Comment by NaamloosDT** [comment] 2019-05-28 18:42
yikes

**Comment by Neuheit** [comment] 2020-09-26 19:00
Closing this issue because I could not reproduce and due to inactivity. Feel free to reopen if you are still experiencing this.

**Closed by Neuheit** 2020-09-26 19:00 UTC
Labels: bug, core, v4.x
