### ISSUE TITLE
Event handler exception massive spam

### ISSUE THREAD

**Issue by Lymdun** [DSharpPlus/DSharpPlus#711] opened 2020-12-15 16:47 UTC
# Summary
My console is being flooded of event handler exception for no reason. Mostly of **MESSAGE_REACTION_ADDED** even nothing in my code is using reactions.

# Details
First of all, I've confirmed that the bug is not coming from my code on the Discord server. As a proof, it happens even when no commands are registered at all. It also happens when setting **UseDefaultCommandHandler** as true. Also, as you can read on the stacktrace, it is pointing internal code (**defined in [...]**).
Stacktrace: https://pastebin.com/W4pUHwt7
Code example: https://pastebin.com/NyBYBhKF

I'm using Net5.0, but it was also happening on Net core 3.1.
The **MESSAGE_REACTION_ADDED** exceptions are happening **only** when shards are booting up.

# Notes
It might be related, but I'm getting a lot of errors about MESSAGE_CREATED exception when I'm using my own async handler for MessageCreated, even though everything is wrapped on a Task.Run. (And occurs even when all shards are loaded)
Only happens on Linux Debian 10 production machine. Works perfectly fine on Windows.
I know you would want a repro project, but it seems to happens only when lot of shards & guilds are being loaded up. (In my case, 70k guilds & 40 shards)

**Comment by Emzi0767** [comment] 2020-12-15 19:28
Do you have a link to a usable paste?

**Comment by jhendershott** [comment] 2021-01-13 03:48
@Emzi0767 I'm having the same issue

https://pastebin.com/Ss8nsfzX

**Comment by Neuheit** [comment] 2021-01-13 04:06
> @Emzi0767 I'm having the same issue or very similar issue. it doesn't seem to affect much other than my logs
> 
> https://pastebin.com/Ss8nsfzX

Make sure you move your event handler code off the gateway thread (Task.Run).

**Comment by Lymdun** [comment] 2021-01-22 18:35
> Do you have a link to a usable paste?

It doesn't matter what MessageReceivedAsync does, even with a simple ``return`` the issue happens to me

**Comment by Speyd3r** [comment] 2021-01-22 18:40
Maybe something to do with intents?

**Comment by Kiritsu** [comment] 2021-01-23 04:20
Is your Debian 10 machine somehow having difficulties regarding its performances when the shards are booting? Check the RAM and CPU usage. If it has troubles it may make everything slower and so making these events take more time than expected to complete?

**Comment by Lymdun** [comment] 2021-01-23 12:55
> Maybe something to do with intents?

I doubt so, once shards are loaded, everything works fine.

> Is your Debian 10 machine somehow having difficulties regarding its performances when the shards are booting? Check the RAM and CPU usage. If it has troubles it may make everything slower and so making these events take more time than expected to complete?

RAM/CPU usage was more than fine. My guess is that these events are called during boot up while it shouldn't

**Comment by Neuheit** [comment] 2021-02-01 22:39
This appears to be due to interactivity using/waiting for these events under the hood. Looking at how it hooks the `DiscordClient` events, it appears to be doing things properly so I'm not sure why these errors are appearing. Regardless I feel we should try to implement a way to filter out these messages for our internal event handlers.

**Comment by Naamloos** [comment] 2021-03-04 21:32
Interactivity offloading it's tasks is not _necessarily_ fully going to fix this specific issue. Interactivity's methods by design block a Task waiting for it's results. This issue itself is likely fixed by using Task.Run, but it might still in some cases throw exceptions because (as stated in #781) interactivity's own events are _not_ using Task.Run.

**Closed** 2021-03-11 21:19 UTC
Labels: bug, interactivity, v4.x
