### ISSUE TITLE
GetNextMessageAsync returns null Results

### ISSUE THREAD

**Issue by redstarxx** [DSharpPlus/DSharpPlus#1344] opened 2022-07-15 09:48 UTC
# Summary
After using the `MessageExtension.GetNextMessageAsync` method (with or without parameters) on a `DiscordMessage` object, accessing the returned `Results` property causes `NullReferenceException`.

# Details
The length of time it took for the NRE to occur from the point `GetNextMessageAsync` is called is equivalent to the time specified in the interactivity configuration timeout. The NRE occurs even if you haven't sent anything into the respective channel. 

# Steps to reproduce
1. Send a message into a channel,
2. Use the `GetNextMessageAsync` method on the message object,
3. Enter a random word,
4. Try to access the `Results` property and it should be null.

**Comment by OoLunar** [comment] 2022-07-15 22:18
Confirmed bug, not because of the NRE but because GetNextMessageAsync isn't properly getting the next message causing the method to timeout (as seen in `InteractivityResult<DiscordMessage>.TimedOut`). Here's a repro:
```cs
InteractivityResult<DiscordMessage> nextMessage = await context.Message.GetNextMessageAsync();
if (nextMessage.TimedOut)
{
    await context.RespondAsync("Timed out.");
    return;
}
else
{
    await context.RespondAsync($"Message by {nextMessage.Result.Author.Username}:\n{nextMessage.Result.Content}");
}
```
Unofficially assigning @DWaffles if they wish to take up the issue

**Comment by OoLunar** [comment] 2022-07-16 07:29
Doing some debugging, it seems everything is registered correctly. The MatchRequest is successfully registered to the `ConcurrentHashSet _matchrequests` property in the `EventWaiter` class, the predicate is filled with the correct variables and the timeout occurs as expected.

What isn't expected is that `EventWaiter.HandleEvent` isn't executed until the `_matchrequests` variable is empty (which is when the match request has timed out and is removed)

**Comment by zontreck** [comment] 2022-07-25 14:20
Is there a workaround for this?

**Comment by zontreck** [comment] 2022-12-06 09:43
It's the timing out that is the issue, the code never gets executed. At least it didn't when I was debugging it and trying to find the exact source. @OoLunar mentioned this in a above post too.

Dec 5, 2022 6:12:11 PM Velvet ***@***.***>:

**Comment by Plerx2493** [comment] 2023-10-17 09:41
I think this issue was fixed, can´t repoduce anymore

**Comment by OoLunar** [comment] 2023-10-22 18:13
Closing as unable to reproduce on latest nightlies.

**Closed by OoLunar** 2023-10-22 18:13 UTC
Labels: bug, interactivity
