### ISSUE TITLE
Deadlock with DiscordClient.Dispose().

### ISSUE THREAD

**Issue by Neuheit** [DSharpPlus/DSharpPlus#561] opened 2020-04-25 04:26 UTC
# Summary
Calling `DiscordClient.Dispose()` immediately after ready will create a deadlock.

# Details
This only occurs when calling Dispose immediately after ready, and works fine when calling it immediately after ConnectAsync or waiting until after ready. 

# Steps to reproduce
1. Create a discord client and call ConnectAsync()
2. Wait for ready to fire in the same method.
3. Call Dispose().
4. Observe that the rest of the main method is not called.

**Comment by PeskyTheBear** [comment] 2020-04-25 16:04
# Summary
I think this issue is caused because WebSocketClient.DisconnectAsync() closes the internal websocket before the receiving loop is finished receiving the heartbeat that has just been send to Discord. This means the receiving loop will be stuck trying to receive the message. 
# Detailed


In the DisconnectAsync() function of the WebSocketClient the websocket _wc_ is closed before the receiving loop is told to stop running using the __receiverTokenSource_.
```C#
public async Task DisconnectAsync(int code = 1000, string message = "")
{
    // Ensure that messages cannot be sent
    await this._senderLock.WaitAsync().ConfigureAwait(false);

    try
    {
        this._isClientClose = true;
        if (this._ws != null)
            await this._ws.CloseOutputAsync((WebSocketCloseStatus)code, message, CancellationToken.None).ConfigureAwait(false);

        if (this._receiverTask != null)
            await this._receiverTask.ConfigureAwait(false); // Ensure that receving completed

        // Cancel all running tasks
        if (this._socketTokenSource != null)
        {
            this._socketTokenSource.Cancel();
            this._socketTokenSource.Dispose();
        }

        if (this._receiverTokenSource != null)
        {
            this._receiverTokenSource.Cancel();
            this._receiverTokenSource.Dispose();
        }
    }
    catch (Exception ex) { }
    finally
    {
        this._senderLock.Release();
    }
}
```
This creates the posibility that the message is not fully received before the websocket __wc_ is closed.
```C#
 while (!token.IsCancellationRequested)
     {
        WebSocketReceiveResult result;
        byte[] resultBytes;
        do
        {
             result = await this._ws.ReceiveAsync(buffer, CancellationToken.None).ConfigureAwait(false);
             if (result.MessageType == WebSocketMessageType.Close)
             break;

             bs.Write(buffer.Array, 0, result.Count);
        }
        while (!result.EndOfMessage);
        // function continues 
``` 
# Proposed Fix
What I'm proposing to fix this issue would be to cancel all running tasks first and wait for the receivingTask to be completed before closing the websocket, as shown in the following:
```C#
public async Task DisconnectAsync(int code = 1000, string message = "")
{
    // Ensure that messages cannot be sent
    await this._senderLock.WaitAsync().ConfigureAwait(false);

    try
    {
        // Cancel all running tasks before closing the websocket
        if (this._socketTokenSource != null)
        {
            this._socketTokenSource.Cancel();
            this._socketTokenSource.Dispose();
        }

        if (this._receiverTokenSource != null)
        {
            this._receiverTokenSource.Cancel();
            this._receiverTokenSource.Dispose();
        }
        
        if (this._receiverTask != null)
            await this._receiverTask.ConfigureAwait(false); // Ensure that receving completed

        
        this._isClientClose = true;
        if (this._ws != null)
            await this._ws.CloseOutputAsync((WebSocketCloseStatus)code, message, CancellationToken.None).ConfigureAwait(false);
    }
    catch (Exception ex) { }
    finally
    {
        this._senderLock.Release();
    }
}
```
# Tesing
This has been tested to work in the scenario described above and in a scenario where the bot is allowed to work but is disposed after a certain amount of time.

**Comment by Emzi0767** [comment] 2020-04-25 16:53
There's no dedicated heartbeat receiver - these are received with all the other events. Canceling then waiting was what we moved away from as that caused the client to be unable to reconnect at all. Reason this happens the way it does is because we wait for the client to drain the event queue.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by PeskyTheBear** [comment] 2020-04-25 19:30
Okay i looked some more and found that the following is likely to be happening.

The DisconnectAsync() of the WebSocketClient gets called at around the same time as when the ReceiverLoopAsync() gets the message with the opcode Hello from discord. What the 

DisconnectAsync() will do is lock the _senderLock in the WebClient. It will then close the webSocket and wait for the receiverLoop to finish. 

After a little bit of time the DiscordClient.OnHelloAsync() will be called (and the receiverLoop is awaiting this). In this method SendIdentifyAsync will be called. Here a new message will be send to Discord using the WebSocketClient.SendMessageAsync() which will wait for the _senderLock. 

The problem is that the _senderLock is still claimed by  DisconnectAsync() which in turn is waiting for the receiverLoop to be finished. This seems to be a reasonable explanation for the deadlock.

**Comment by PeskyTheBear** [comment] 2020-04-26 18:27
I might have a fix this time that takes the receiving in to account. Namely add a check on the start of SendMessageAsync in the WebSocketClient so it wont try to acquire the  the lock, as shown in the snipped below. This has been tested to fix the issue and it does not seem to break any normal functionality.

``` C#
public async Task SendMessageAsync(string message)
{
    if (this._ws == null || this._isClientClose)
        return;

    var bytes = Utilities.UTF8.GetBytes(message);
    await this._senderLock.WaitAsync().ConfigureAwait(false);
    try
    {
```

**Closed** 2020-06-12 21:30 UTC
Labels: bug, core, v4.x
