### ISSUE TITLE
DiscordGuild.GetRole returns null on .net core 3.0 linux arm

### ISSUE THREAD

**Issue by red031000** [DSharpPlus/DSharpPlus#477] opened 2019-10-19 02:12 UTC
# Summary
DiscordGuild.GetRole returns null, leading to a NullReferenceException when trying to modify this role on linux arm .net core 3.0, this did not happen on .net core 2.2

# Details
My bot is a specially crafted bot for TwitchPlaysPokemon, it takes info from the stream api and puts it in a discord channel. When significant events happen, it announces it in a news channel, and pings a role. This role has mentionable off by default, so the bot turns it on, pings, then turns it off. The exact code can be seen here: https://github.com/red031000/StreamFeedBot/blob/master/StreamFeedBot/Utils.cs#L59

The role is able to be pinged when it is manually set to mentionable prior to the announcement.

When attempting to get the role, the method returns null for the role, even though it exists, the ID is correct (I checked it 3 times), and it was working fine on .net core 2.2.

since .net core 3.0 has been released, I upgraded to it to take advantage of nullable reference types. testing on windows is fine, the bot is able to grab the role without problem, however, when moving it to my server (a raspberry pi 3b, using `dotnet publish -r linux-arm`), the role returned is null, and therefore is not able to be modified to be pingable. I am using visual studio 2019, and publishing with dotnet 3.1.100-preview1-014459. I am using the default discord client, and the latest preview version of DSharpPlus (4.0.0-nightly-00625). The operating system is raspbian 10 (buster), console only.

Stacktrace of the exception:

```
Object reference not set to an instance of an object.
   at StreamFeedBot.Utils.AnnounceMessage(String message, DiscordClient client) in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Utils.cs:line 68
   at StreamFeedBot.Program.MainLoop() in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Program.cs:line 233
```

# Steps to reproduce
1. Use the default discord client
2. Use Client.GetRole for a role that exists
3. Deploy to raspberry pi using dotnet publish, run the given executable
4. Role will be null

# Notes
I have taken reasonable attempts to ensure that it is not something that I've changed, I have tested on .net core 2.2, and it works fine, I have also tested on 3.0 on windows, and it also works fine. I have used debug logging to ensure that the role is indeed null (as you can probably see in the code). To prevent this from happening, I will revert back to 2.2 until this is fixed.

**Comment by uwx** [comment] 2019-10-19 02:28
This is a bit of a specific issue. I think there might be an inconsistency in your test set. Does this occur for all roles on all servers? Does this occur on x86 Linux? Are you waiting for the appropriate event to make sure the role is cached first?

I'd imagine either one of two scenarios
- You're calling GetRole too soon and your guild is a skeleton object
- Some exception was swallowed and the guild is left incomplete, which I hoped I'd completely prevented from happening, but I guess that's the only reason?

Also, please post anything suspicious in your logs if found.

**Comment by red031000** [comment] 2019-10-19 02:33
The code is called after several hours of it being started (usually about 4 or 5 hours after) so I should hope it's not an issue of being called too early, I will test x86 linux and every role on all servers I can as well

**Comment by red031000** [comment] 2019-10-20 19:33
interesting side note: while testing I did get a `System.MemberAccessException Type initializer was not callable.` when calling DiscordClient.GetGuildAsync on linux x64, which I'm assuming is related to #431. it was pretty quickly after client was connected, so it could be due to that. it also does not occur on windows

**Comment by red031000** [comment] 2019-10-20 20:03
(edited it a bit for clarity, I wrote this issue at 3am...)

**Comment by Emzi0767** [comment] 2019-10-20 20:08
@uwx this might be related to concurrent dictionaries and how they are serialized/deserialized. Might wanna look into this.

**Comment by red031000** [comment] 2019-10-20 20:11
further looking into this, a lot of exceptions were swallowed on connecting, three of the same, here's the exception:
```
[Websocket] Error: Socket swallowed an exception:
System.MemberAccessException: Type initializer was not callable.
   at System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|60_1(SocketMessageEventArgs e) Type initializer was not callable.
   at System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|60_1(SocketMessageEventArgs e)

**Comment by uwx** [comment] 2019-10-20 20:27
Oh, fuck. This is a duplicate of #431. I can't test this, because I don't have an ARM64 machine, but the fix should be changing this line:

https://github.com/DSharpPlus/DSharpPlus/blob/50311177aef1c0617bc45172da0d120e3fd64811/DSharpPlus/Net/Serialization/SnowflakeArrayAsDictionaryJsonConverter.cs#L38

To `.FirstOrDefault(e => !e.IsStatic && e.GetParameters().Length == 0);` 

If anyone wants to try, please do. I wanna get this working on all platforms.

**Comment by red031000** [comment] 2019-10-20 20:30
I did get a few other errors, trying to extract them

**Comment by red031000** [comment] 2019-10-20 20:37
exception, possibly unrelated? ```
DEBUG: ROLE IS NULL!
Announced message: <@&413003203274080267> Test from linux
[Event] Warning: Could not find channel last message belonged to.
[DSharpPlus] Error: An System.AggregateException occurred in MESSAGE_CREATED.
System.AggregateException: Exceptions occured within one or more event handlers. Check InnerExceptions for details. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.EventArgs.MessageCreateEventArgs.get_Guild()
   at StreamFeedBot.Program.DmHandler(MessageCreateEventArgs e) in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Program.cs:line 233
   at DSharpPlus.AsyncEvent`1.InvokeAsync(T e)
   --- End of inner exception stack trace --- Exceptions occured within one or more event handlers. Check InnerExceptions for details. (Object reference not set to an instance of an object.)

Inner Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.EventArgs.MessageCreateEventArgs.get_Guild()
   at StreamFeedBot.Program.DmHandler(MessageCreateEventArgs e) in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Program.cs:line 233
   at DSharpPlus.AsyncEvent`1.InvokeAsync(T e) Object reference not set to an instance of an object.
   at DSharpPlus.EventArgs.MessageCreateEventArgs.get_Guild()
   at StreamFeedBot.Program.DmHandler(MessageCreateEventArgs e) in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Program.cs:line 233
   at DSharpPlus.AsyncEvent`1.InvokeAsync(T e)

**Comment by uwx** [comment] 2019-10-20 20:39
Probably a side effect of the same deserialization issue.

**Comment by red031000** [comment] 2019-10-20 20:41
also had
``
[Websocket:Dispatch] Warning: Invalid payload body, you can probably ignore this message: Dispatch:PRESENCES_REPLACE
[]
```but I guess that's not really a problem

**Comment by uwx** [comment] 2019-10-20 20:42
That one is out of our control.

**Comment by red031000** [comment] 2019-10-20 20:47
if someone wants to make the change and provide me with a build I can check to make sure it is resolved

**Comment by uwx** [comment] 2019-10-20 20:54
@red031000
https://drive.google.com/open?id=1ZjMSfE-r_96NfGHW5XW9mIXixcqBHqlq

**Comment by red031000** [comment] 2019-10-20 21:19
got
```
Exception has occured: Microsoft WebSocket client is not supported on this platform. You need to target .NETFX, .NET Standard 1.3, or provide a WebSocket implementation for this platform.
   at DSharpPlus.Net.WebSocket.WebSocketClient..ctor(IWebProxy proxy)
   at DSharpPlus.Net.WebSocket.WebSocketClient.CreateNew(IWebProxy proxy)
   at DSharpPlus.DiscordClient.InternalConnectAsync()
   at DSharpPlus.DiscordClient.ConnectAsync(DiscordActivity activity, Nullable1 status, Nullable1 idlesince)
   at StreamFeedBot.Program.MainAsync() in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Program.cs:line 131
   at StreamFeedBot.Program.Main() in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Program.cs:line 50

**Comment by uwx** [comment] 2019-10-20 21:19
oh fuck

**Comment by uwx** [comment] 2019-10-20 21:19
SECOND TRY https://drive.google.com/open?id=1fuc_eo6ym1_HYoLrcGS4Chmdp36Poa0W

**Comment by red031000** [comment] 2019-10-20 21:37
seems to work fine

**Comment by red031000** [comment] 2019-10-20 21:38
the issue was fixed by that build

**Closed** 2019-10-21 07:04 UTC
Labels: bug, core
