### ISSUE TITLE
VoiceNext doesn't return a VoiceNextConnection, despite connecting to the channel

### ISSUE THREAD

**Issue by IanJCV** [DSharpPlus/DSharpPlus#1247] opened 2022-03-26 20:25 UTC
# Summary
VoiceNext connects to a channel, but doesn't return a reference to the connection, or add it to the ActiveConnections Dictionary.

# Details
There aren't any exceptions, errors, or debug/trace calls. Both GetVoiceNext().ConnectAsync(channel) and channel.ConnectAsync() exit out of the method on call and don't return anything. Trying to retrieve a connection through VoiceNextExtension.GetConnection(guild) don't do anything, and stepping through the code shows that the ActiveConnections Dictionary is empty the entire way through.

The bot has Admin persmissions, the setup works fine, and trying to get a ref to VoiceNext through Client.GetVoiceNext() works fine.

Win10x64
.NET Core 3.1
VS2022
D#+ 4.1.0 (Latest stable, nightly builds don't work either though)  

```cs
        [Command("join")]
        public async Task JoiningCommand(CommandContext ctx, DiscordChannel channel = null)
        {
            channel = ctx.Member.VoiceState?.Channel;
            connection = await ctx.Client.GetVoiceNext().ConnectAsync(channel); // Quits here and doesn't return
            // connection = await channel.ConnectAsync(); // Doesn't work either
            Console.WriteLine("connected"); // Never gets to this line
        }
```

# Notes
I've already tried stepping through the code a million times, downloaded the Natives package on NuGet, downloaded the opus and sodium dlls manually, renamed them, put them everywhere (root, runtimes folder, next to the solution, etc), and tried the nightly builds. Nothing works.

**Comment by OoLunar** [comment] 2022-03-26 22:38
Will look into it shortly. Thank you very much for your hard work in creating this issue.

**Comment by Kiritsu** [comment] 2022-03-26 22:39
This happens when you don't have the opus/sodium binaries installed or present next to your executable. Exceptions are sometimes silently swallowed so it's kinda hard to debug as a library user.

**Comment by AutismSpirit** [comment] 2022-03-26 22:49
> This happens when you don't have the opus/sodium binaries installed or present next to your executable.  

I have libopus.dll, libsodium.dll, opus.dll, and sodium.dll right next to the EXE. I mentioned this in my notes. They're also in (root)/runtimes/win-x64/native. I also have VoiceNext.Natives installed.  
I'm running Windows 10 21H1, the one just before latest.

**Comment by OoLunar** [comment] 2022-03-26 23:26
I can reproduce this on Void Linux, latest nightly (`4.2.0-nightly-01101`) with the following code:
![image](https://user-images.githubusercontent.com/46751150/160260246-3760e2a3-4bc7-4ce5-9f1a-79ea00417daf.png)

```cs
// await DiscordShardedClient.UseVoiceNextAsync(new VoiceNextConfiguration() { });

namespace Tomoe.Commands.Common
{
    public class JoinVC : BaseCommandModule
    {
        [Command("join")]
        public async Task JoiningCommand(CommandContext ctx, DiscordChannel? channel = null)
        {
            channel ??= ctx.Member.VoiceState?.Channel;
            VoiceNextConnection? connection = await ctx.Client.GetVoiceNext().ConnectAsync(channel); // Quits here and doesn't return
            // connection = await channel.ConnectAsync(); // Doesn't work either
            Console.WriteLine("connected"); // Never gets to this line
        }
    }
}
```

<details>

```log
The program '[18137] Tomoe.dll' has exited with code 0 (0x0).
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Tomoe.dll'. Symbols loaded.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'Tomoe.Program.<Main>'
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/DSharpPlus.CommandsNext.dll'. Symbols loaded.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/DSharpPlus.dll'. Symbols loaded.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/DSharpPlus.Interactivity.dll'. Symbols loaded.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/DSharpPlus.VoiceNext.dll'. Symbols loaded.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Emzi0767.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'Tomoe.Program.Main'
Step into: Stepping over non-user code 'Tomoe.Program.<Main>d__12..ctor'
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Configuration.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Configuration.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Configuration.EnvironmentVariables.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Configuration.CommandLine.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Logging.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.EntityFrameworkCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.DependencyInjection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Logging.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Configuration.Binder.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Serilog.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'Tomoe.Program.<>c__DisplayClass12_0..ctor'
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.FileProviders.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Configuration.FileExtensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.FileProviders.Physical.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.IO.FileSystem.Watcher.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.FileSystemGlobbing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Text.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Text.Encoding.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Options.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Serilog.Sinks.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Serilog.Sinks.File.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Serilog.Enrichers.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Serilog.Extensions.Logging.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.InteropServices.RuntimeInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Reflection.Emit.ILGeneration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Diagnostics.Tracing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Net.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Threading.Channels.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Threading.Tasks.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Linq.Expressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Diagnostics.DiagnosticSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Net.Security.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.X509Certificates.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Net.Sockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Net.NameResolution.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Formats.Asn1.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.OpenSsl.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.Serialization.Formatters.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Diagnostics.TraceSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Runtime.Serialization.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Data.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Private.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'Anonymously Hosted DynamicMethods Assembly'.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.EntityFrameworkCore.Relational.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/SixLabors.Fonts.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Caching.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Npgsql.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Npgsql.EntityFrameworkCore.PostgreSQL.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/EFCore.NamingConventions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.EntityFrameworkCore.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Transactions.Local.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Net.NetworkInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/Microsoft.Extensions.Caching.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.ComponentModel.Annotations.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[2022-03-26 18:18:32.278 -05:00] [WARN] [10] Microsoft.EntityFrameworkCore.Model.Validation: The property 'AutoModel<IMention>.Values' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Collections.Specialized.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Linq.Queryable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/lunar/Code/Lunar/Tomoe/bin/Debug/net6.0/ConcurrentCollections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[2022-03-26 18:18:34.225 -05:00] [INFO] [10] DSharpPlus.BaseDiscordClient: DSharpPlus, version 4.2.0
[2022-03-26 18:18:34.226 -05:00] [INFO] [10] DSharpPlus.BaseDiscordClient: Booting 1 shards.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.IO.Compression.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Net.WebSockets.Client.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Net.WebSockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Security.Cryptography.Algorithms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[2022-03-26 18:18:35.075 -05:00] [INFO] [12] DSharpPlus.BaseDiscordClient: Booted shard 0.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Threading.Tasks.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/src/dotnet-sdk-6.0.2/shared/Microsoft.NETCore.App/6.0.2/System.Reflection.Emit.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```
</details>

(note that `connected` never get's sent out to Console)

**Comment by AutismSpirit** [comment] 2022-03-26 23:36
I don't know the codebase very well, so I can't really look for a solution, but do you guys have any ideas on why this would be happening?

**Comment by OoLunar** [comment] 2022-03-26 23:38
We're not receiving/correctly processing the VNext gateway events from Discord. Confirmed library bug.

**Comment by Kiritsu** [comment] 2022-03-27 01:40
After investigation I forgot to Task.Run my testing code (since I was too lazy to setup cnext) which was causing the event deadlock (makes sense)

I finally tested with this piece of code (https://paste.alnmrc.com/tuhicuvobi.cs) and appropriate permissions (cause the Gateway will never respond and will deadlock the ConnectAsync if permissions are unnecessary) and it works just fine, so I can't reproduce (master branch).

**Comment by AutismSpirit** [comment] 2022-03-27 01:50
> appropriate permissions (cause the Gateway will never respond and will deadlock the ConnectAsync if permissions are unnecessary)

Do bots need anything special to not deadlock ConnectAsync? My bot has Admin permissions, and intents set to AllUnprivileged. What does "will deadlock if persmissions are unnecessary" mean?

**Comment by Kiritsu** [comment] 2022-03-27 10:23
Permission to view / connect to the channel should be enough... On my test I tried with all intents but should also work with all unprivileged

**Comment by OoLunar** [comment] 2023-03-23 18:16
@RageMellon ensure you're using the latest nightly

**Comment by RageMellon** [comment] 2023-03-23 18:30
I'm using `4.4.0-nightly-01449` for both `DSharpPlus.VoiceNext` and `DSharpPlus`

**Comment by OoLunar** [comment] 2023-03-23 18:33
I'm currently writing my own voice extension. Once I can get it to connect correctly and as intended, I will attempt to look into VNext once more. The code there is very convoluted and difficult to maintain, so it may be awhile. Apologies for the inconvenience

**Comment by RageMellon** [comment] 2023-03-23 18:45
Thanks! Would your code be a replacement for VNext, or will that be a different Discord Library?

**Comment by OoLunar** [comment] 2023-03-23 21:43
> Thanks! Would your code be a replacement for VNext, or will that be a different Discord Library?

It would be it's own separate extension, similar to CNext, Slashies, Lavalink, etc

**Comment by airbreather** [comment] 2023-03-28 07:29
> Now, I get the same as the above. It seems that `ConnectAsync` is deadlocking :cry:

Even though the latest nightly didn't work for this person, I also had a disruption in my last weekly Friday session that looked a lot like this, which I **was** able to resolve by switching to the latest nightly.  There's also [a recent report on the Discord](https://discord.com/channels/379378609942560770/1087711096787439726) that this person also resolved by switching to a nightly build.

I strongly suspect that 54f1717b is what's been unblocking people in my situation: the old format [has been deprecated for over 3 years now](https://discord.com/developers/docs/change-log#ip-discovery-updates), and in fact Discord [recently announced](https://discord.com/channels/379378609942560770/753784098413084722/1080626257751986257) that this would start happening.

If a new minor version bump to "stable" is still a bit further down the road, what are your thoughts about cherry-picking 54f1717b to https://github.com/DSharpPlus/DSharpPlus/tree/release/4.3 and pushing out a 4.3.1, per this bit in the README?

> Critical bugfixes in the nightly releases will usually be backported to the latest major stable release, but only after they have passed our soak tests.

**Comment by VelvetThePanda** [comment] 2023-03-28 07:33
Hi! Sorry about the lack of attention to this issue; it's been brought up across the Discord the last week and we've been trying to make sure everything is in order for us to make a 4.4 stable release in an expedited manner. That will hopefully happen soon given there's nothing major on our backlog. Thank you for your patience on this regardless. :)

**Comment by VelvetThePanda** [comment] 2023-03-28 07:35
> If a new minor version bump to "stable" is still a bit further down the road, what are your thoughts about cherry-picking [54f1717](https://github.com/DSharpPlus/DSharpPlus/commit/54f1717b37d66c4dd0a457c2b13822afc9e70e56) to https://github.com/DSharpPlus/DSharpPlus/tree/release/4.3 and pushing out a 4.3.1, per this bit in the README?

I do think this is something we should've done prior, but I don't recall anyone bringing it up since this was a non-issue when that commit was added. Though, with 4.4 stable right around the corner I think it's better that we just ship that, since it has a lot of fixes and features that're long overdue anyways. cc @akiraveliara

**Comment by akiraveliara** [comment] 2023-03-28 15:59
update: 4.4.0 is out now, let us know if a 4.3.1 containing the VNext fix would be useful for you

**Comment by airbreather** [comment] 2023-03-29 10:18
> let us know if a 4.3.1 containing the VNext fix would be useful for you

Not for me, thanks though.

**Closed** 2023-10-05 19:18 UTC
Labels: bug, voicenext
