### ISSUE TITLE
Object ref not set to an instance of an object when creating a Direct Message after longer uptime

### ISSUE THREAD

**Issue by BlackLotusLV** [DSharpPlus/DSharpPlus#1989] opened 2024-07-10 13:57 UTC
### Summary

Throws an error of reference not set when attempting to create a DM to a user after the bot has been up for a longer period of time. This does not occur on start up rather after a while the bot has run. Only fix is to hard restart the application.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Reproduction Steps

Slash command that triggers the error after longer runtime.
The command in question: https://hst.sh/refiwexepo.csharp

### Exceptions or other error messages

```txt
An unexpected error occurred: Object reference not set to an instance of an object.
   at DSharpPlus.Entities.DiscordUser.<CreateDmChannelAsync>b__77_1(DiscordUser y)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DSharpPlus.Entities.DiscordUser.<CreateDmChannelAsync>b__77_0(DiscordDmChannel x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DSharpPlus.Entities.DiscordUser.CreateDmChannelAsync()
   at DSharpPlus.Entities.DiscordUser.SendMessageAsync(DiscordMessageBuilder message)
   at TheCrewCommunity.LiveBot.Commands.General.OpenModMailCommand.ExecuteAsync(SlashCommandContext ctx, String subject) in C:\Users\melna\RiderProjects\TheCrewCommunity\TheCrewCommunity\LiveBot\Commands\General\OpenModMailCommand.cs:line 56
   at TheCrewCommunity.LiveBot.Commands.General.OpenModMailCommand.ExecuteAsync(SlashCommandContext ctx, String subject) in C:\Users\melna\RiderProjects\TheCrewCommunity\TheCrewCommunity\LiveBot\Commands\General\OpenModMailCommand.cs:line 73
   at DSharpPlus.Commands.Invocation.CommandEmitUtil.<>c__DisplayClass2_0.<<GetTaskFunc>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DSharpPlus.Commands.DefaultCommandExecutor.ExecuteCoreAsync(CommandContext context)
```

**Comment by Plerx2493** [comment] 2024-07-10 16:43
Short investigation shows that this bug is likely caused by a `DiscordDMChannel` in the clients cache with its `Recipents` beeing `Null`. I was not able to finde the root cause

**Comment by Erisa** [comment] 2024-07-11 11:47
I experienced this as well and it was indeed because of a DM channel entry with a null recipient ending up in cache:

```json
  "<userid>": {
    "permission_overwrites": [],
    "recipients": [
      null
    ],
    "owner_id": 0,
    "application_id": 0,
    "parent_id": null,
    "type": 1,
    "position": 0,
    "rate_limit_per_user": null,
    "nsfw": false,
    "permissions": null,
    "id": 1102596241579331605
  },```
redacted user ID for privacy but note how the channel has a recipient that is `null`

I am on `5.0.0-nightly-02302+03db404e8351d5d0d2c14108ce9879e226791ccb`

Pretty sure the relevant code is here

https://github.com/DSharpPlus/DSharpPlus/blob/a056dc833a48c259f52cc90d32f73bfa550ac54a/DSharpPlus/Entities/User/DiscordUser.cs#L265-L268

and while I don't know the root cause either, it can be fixed by adding a null check in there when searching recipients.

**Comment by Plerx2493** [comment] 2024-07-11 11:52
yeah already found the specific code where it throws. I will open a hotfix pr and leave this issue open until we found the root cause. Also #1919 is unrelated because `SingleOrDefault` would also throw if the `recipients` are `null`.

**Comment by akiraveliara** [comment] 2024-10-11 12:20
cannot reproduce, the code now includes a null check

**Closed by akiraveliara** 2024-10-11 12:20 UTC
Labels: core
