### ISSUE TITLE
Replies do not mention when toggled to.

### ISSUE THREAD

**Issue by VelvetThePanda** [DSharpPlus/DSharpPlus#731] opened 2021-01-14 09:27 UTC
Make sure you familiarize yourself with our contributing guidelines.

# Summary
With #704 merged, inline replies were added, as well as the DiscordMessage builder, however, using the builder to add replies do not set the requisite "replied_user" to true, which toggles the mention.

# Details
This has been tested on Windows 10, and Ubuntu 20.04 LTS, both using .NET 5, nightly build #00777

Using `CommandContext#RespondAsync(DiscordMessageBuilder)` override does not properly mention, but `DiscordEmbedBuilder#SendAsync(DiscordChannel)` does.

# Steps to reproduce
- Create message builder in a command
- Add content or embed so there's a valid message
- Add a reply of your choosing, and set reply to true

- Send via the command context
- Send via the builder

- Observe.

**Comment by jeffreyladd** [comment] 2021-01-14 13:28
@VelvetThePanda can you please provide a usecase or actual code.  Cause using the code below works perfect for me
`
[Command, Priority(0)]
        public async Task ReplyAsync(CommandContext ctx, [RemainingText]string response = "")
        {
            var builder = new DiscordMessageBuilder();

            if (string.IsNullOrEmpty(response))
            {                
                builder.WithContent("This is a reply! :)");   
            }
            else
            {
                builder.WithContent($"You requested me to say \"{response}\"");
            }

            builder.WithReply(ctx.Message.Id, true);
            await ctx.RespondAsync(builder);
        }
`

#Steps used in testing
1. Adds the above command
2. start bot
3. Set Breakpoint at start of Command
3. goes to discord and types !reply A Test Message.
4. Hit Enter
5. Switch Discord to another server.
6. Go to VS and hit Continue
7. Notice that the server icon i executed the command in says i have a mention and the reply sent is highlighted

![image](https://user-images.githubusercontent.com/26604060/104596792-7672d700-5642-11eb-8c5f-bc6a5c7ba62f.png)

**Comment by VelvetThePanda** [comment] 2021-01-14 13:34
Huh. cc @OoLunar, who also tested this.

Neither of us could get it to work and various other members reported having issues with replies not replying. Though I suspect mingling with replies might break it.

**Comment by VelvetThePanda** [comment] 2021-01-14 13:40
Alright. Pinned it down. Turns out it's not an issue with the builder itself, and this may be an API issue really, but adding the author of the message it's replying to actually disables the mention regardless of if you set it to mention or not. I'll see if this is the case for adding other allowed mentions.

**Comment by VelvetThePanda** [comment] 2021-01-14 13:44
Adding any allowed mentions breaks the reply mention ![As you can see here](https://velvet.is-ne.at/zmBg4O.png)

**Comment by jeffreyladd** [comment] 2021-01-14 13:50
Okay i found the cause, this was a bug way before the message builder was merged into the inline replies branch.  Ill create a new new PR to fix this.

**Comment by JulianusIV** [comment] 2021-01-14 17:34
Addition to this reply
https://github.com/DSharpPlus/DSharpPlus/issues/731#issuecomment-760196784
no need for breaking as on PC there will be a @ infront of the name at the reply if it pinged, which is missing when it did not ping

**Closed** 2021-01-15 08:49 UTC
Labels: bug, core, v4.x
