### ISSUE TITLE
[Commands] Optional enum options in the middle, if left blank cause overflow exception

### ISSUE THREAD

**Issue by BlackLotusLV** [DSharpPlus/DSharpPlus#1795] opened 2024-03-10 08:23 UTC
### Summary

When you have a command that has multiple properties and some are optional. If you have a enum options for one in the middle, if you leave it blank it will cause a overflow exception
Command that made me find out about this
```
    [Command("warn"), Description("Warns a user"), RequirePermissions(Permissions.KickMembers)]
    public async Task Warn(SlashCommandContext ctx,
        [Description("User to warn")] DiscordUser user,
        [Description("Why the user is being warned")] string reason,
        [Description("How long the warning will last")] WarnCommand.TimeOutOptions timeOut = 0,
        [Description("Image to attach to the warning")] DiscordAttachment? image = null)
        => await WarnCommand.ExecuteAsync(warningService, ctx, user, reason, timeOut, image);

    public enum TimeOutOptions
        {
            [Description("none")] None = 0,
            [Description("60 secs")] SixtySecs = 60,
            [Description("5 min")] FiveMin = 300,
            [Description("10 min")] TenMin = 600,
            [Description("1 hour")] OneHour = 3600,
            [Description("1 day")] OneDay = 86400,
            [Description("1 week")] OneWeek = 604800
        }
```

Not filling out the following option, or inverting them so the enum is last, does not cause an issue. Issue caused when unfilled enum option is followed by a filled option

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Win11

### Reproduction Steps

Create a command that has optional properties, where one is an enum that is followed by another optional property. Simply leave the enum one blank when executing and fill out the following one.

### Exceptions or other error messages

```txt
[2024:03:10 10:20:41 ERR] [202|CMDError    ] blacklotus(86725763428028416) tried executing 'Mod warn' command, but it errored
DSharpPlus.Commands.Exceptions.ArgumentParseException: Failed to parse timeOut.
 ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(UInt64 value)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at DSharpPlus.Commands.Converters.EnumConverter.ConvertAsync(ConverterContext context, InteractionCreateEventArgs eventArgs)
   at DSharpPlus.Commands.Processors.BaseCommandProcessor`4.ExecuteConverterAsync[T](TConverter converter, TConverterContext converterContext, TEventArgs eventArgs)
   at DSharpPlus.Commands.Processors.BaseCommandProcessor`4.ParseArgumentsAsync(TConverterContext converterContext, TEventArgs eventArgs)
   --- End of inner exception stack trace ---
```

**Comment by BlackLotusLV** [comment] 2024-03-10 12:40
Actually my solution of swapping them around is also not a solution. When swapped around, filling out the timeout field in my command and not providing an image throws a failed to parse image error

**Comment by OoLunar** [comment] 2024-04-11 22:55
Unable to reproduce, closing as fixed by another unrelated PR. If you're able to reproduce it on the latest nightly, please feel free to reopen this issue.

**Closed by OoLunar** 2024-04-11 22:55 UTC
Labels: bug, commands
